name: "HttpAuth"
guid: "d4866cb0-11fb-4f38-b1a5-1efbf870a94d"
version: "1.0.2"
targetAbi: "10.11.10.0"
framework: "net9.0"
owner: "UlysseM"
overview: "Authenticate users using HTTP Headers"
description: >
  Allows to skip the authentification when a http header is provided. Only use this plugin if you know what you're doing.

category: "Other"
artifacts:
  - "Jellyfin.Plugin.HttpAuth.dll"
changelog: |-
  -original version
